### ISSUE TITLE
Support for Kafka 2.0.0?

### ISSUE THREAD

**Issue by jbehrends** [voxpupuli/puppet-kafka#280]
Before I spend a ton of time downloading and setting this up I'm curious if this module works or has been tested with Kafka 2.0.0?

**Comment by PierreR** [comment]
I am sorry to ask but is the  received "supported" tag from the puppet forge still accurate for this module ?
The following is not encouraging:

- not tested on CentOS 7.x
- no compatibility matrix about kafka supported versions in the documentation (meta file)
- the above legitimate above question is not answered and get a thumb down
-  not (real) activity (so it seems) since july 2018

The puppet forge is full of this kind of unsupported modules. I had been used to get quite a nice experience with the wonderful work of voxpupulli. So somehow I am a bit worried and surprised (everyone is leaving the puppet boat ?).

Anyhow enough rambling ...

**Comment by shamil** [comment]
Yes also wondering, is this module still maintained? Any alternatives?

**Comment by PierreR** [comment]
For the record, what I miss the most is an integration with the `cloudera` mirror because that is the only think that seems to work (for me on RHEL 7) with the dependent `deric/zookeeper` module.

**Comment by jbehrends** [comment]
Since starting this issue I've gone ahead and successfully deployed Kafka 2.x without any issues.
For others reference, here are the versions I'm running:

Puppet-5.5.10
CentOS Linux release 7.6.1810
kafka-2.12-2.1.0 ( Scala 2.12 + Kafka 2.1.0 )

**Comment by Fabian1976** [comment]
Same here. Am using this module with Kafka 2.x without any issues. But am thinking of forking this repo for our own to be able to upgrade to stdlib 6.x and archive 4.x

**Comment by dhoppe** [comment]
As you can see, we already have some pull request related to the dependencies. Unfortunately our Travis CI setup ist broken. That is the reason why we have not merged these pull requests or created a new release of this module. :(

**Comment by Fabian1976** [comment]
Good to see it is not a dead repo. Hope to see a new release soon.

**Comment by dhoppe** [comment]
I am closing this issue because the Travis CI pipeline is working again. Currently the module is tested for CentOS 6/7, Debian 8/9/10, Ubuntu 16.04/18.04 and supports Puppet 5/6. 

I am also currently working on an extensive refactoring to modernize the module.
