### ISSUE TITLE
Upgrade to Kafka 0.9.0.0

### ISSUE THREAD

**Issue by cpuchakayaka** [voxpupuli/puppet-kafka#30]
Kafka released a new version 0.9.0.0, can the puppet module be updated to be used with Kafka 0.9.0.0

**Comment by vchan2002** [comment]
I was able to have this module get version 0.9.0.0 by specifying the version number in the class, i.e.

class { 'kafka':
    version      => '0.9.0.0',
  }

**Comment by igalic** [comment]
from https://kafka.apache.org/downloads.html 
> 0.9.0.0 is the latest release. The current stable version is 0.8.2.2.

from what i gather, we should upgrade our default to 0.8.2.2

**Comment by dhoppe** [comment]
It makes sense to use Kafka version 0.9.0.0, even if it is not marked as stable. Because there are some serious bugs which could not be fixed in version 0.8.2.2. 

Using the class parameter to get the latest version of Kafka only works for new setups, because they implemented a new config variable ```inter.broker.protocol.version=0.8.2.X``` for update purposes, as you can see at their [documentation](http://kafka.apache.org/documentation.html#upgrade).

**Comment by Project0** [comment]
kafka-mirror has no daemon option --num.producers anymore (created by template) and wont start with 0.9.0.0.

**Comment by dhoppe** [comment]
I could use some help, as you can see at #56.
